version: "3.9" # composeファイルのバージョン
services:
  app: # サービス名
    build: . # ビルドに使用するDockerfileの場所
    tty: true # コンテナの永続化
    ports: # ホストOSのポートとコンテナのポートをつなげる
      - "8080:8080"
    volumes:
      - ./app:/go/src/app # マウントディレクトリ
    container_name: go-tutorial-app # コンテナ名の固定（indexが付かないように）
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: recordings
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    container_name: go-tutorial-db

volumes:
  db_data:
